### ISSUE TITLE
Way to skip limit in key func with no error

### ISSUE THREAD

**Issue by sliwinski-milosz** [alisaifee/flask-limiter#186]
I am looking for a way to skip limit in a `key_func` if I can't generate the key.

Currently I simply return `None` in `key_func` but that results in following error:
`flask-limiter: ERROR: Skipping limit: 1 per 1 second. Empty value found in parameters.`

Above is useful for example when we try to limit requests that pass specific payload:
```
{
    "user_id": 1234,
    "user_type": "normal"
}
```
Lets say I want to limit only requests that are passed by specific user of `"normal"` type. I don't want to limit requests if `user_type` is different.

My key func would look like:
```
from flask import request

def some_key_func():
    user_id = request.json.get("user_id")
    user_type = request.json.get("user_type")
    if user_id and user_type and user_type=="normal":
        return "{}_{}".format(user_id, user_type)
```

At the moment I am aware of two workarounds:
1. I could use `exempt_when`:
```
exempt_when=lambda: some_key_func() is None
```
But that way I run `some_key_func` twice and I have to pass that `exempt_when` parameter to every single decorator.

2. I can simply filter that error.

Is there any better way to achieve that? Something like returning some `limiter.skip` flag?

**Comment by hellais** [comment]
We also encountered this issue while using the library.

What is the recommended solution to workaround this? 

Ideally there would be an officially supported way of implementing rate limiting white listing, which seems like a fairly common use-case.

Perhaps we could support returning `None` or a special value (`RateLimitWhiteList`?) in the `key_func` and treat that condition as something expected instead of logging an error?

**Comment by alisaifee** [comment]
The recommended way is to indeed use the `exempt_when` approach. If it returns `True` it will actually not run `some_key_func` again since it will short-circuit  the rate limiting before the key is evaluated. I understand that it would be annoying to pass this to each decorator.

If you want to have a global white listing you could use the [request-filter](https://flask-limiter.readthedocs.io/en/stable/#ratelimit-decorator-request-filter) decorator which will skip all rate limiting for a request if the condition is met.

Just to clarify however, when `key_func` returns `None` the rate limiting is just skipped and there isn't any actual error, just a log message in the error.
