### ISSUE TITLE
init_app does not respect enabled status

### ISSUE THREAD

**Issue by CoburnJoe** [alisaifee/flask-limiter#258]
Inside `init_app`, lots of logic and checks happen, even if `enabled` is False. I think it would be good to only perform this work if the limiter is enabled.

Here's my use-case:

- I set a bad `_storage_uri`, e.g. 'not_a_uri`
- `storage_from_string` then raises an exception because this storage uri does not conform to known storage objects = e.g. `redis:/` - even if limiter is not enabled

This is a useful check, but by performing it when the limiting is not enabled, it can cause a problem and frustration.

I'm happy to do the work to implement this change - but I'm not sure of all the areas impacted - from my local testing, it's not just an `if self.enabled` check inside `init_app`, there are other considerations.

**Comment by alisaifee** [comment]
Thank @CoburnJoe. I think you're right. Could you take the [skip-init-on-disabled](https://github.com/alisaifee/flask-limiter/tree/skip-init-on-disabled) branch for a spin and see if that's what you're looking for? The tests aren't very comprehensive and I have a feeling I'm missing something - specially since you mentioned that just the `self.enabled` check inside `init_app` isn't enough.

**Comment by CoburnJoe** [comment]
> Thank @CoburnJoe. I think you're right. Could you take the [skip-init-on-disabled](https://github.com/alisaifee/flask-limiter/tree/skip-init-on-disabled) branch for a spin and see if that's what you're looking for? The tests aren't very comprehensive and I have a feeling I'm missing something - specially since you mentioned that just the `self.enabled` check inside `init_app` isn't enough.

Sorry I've missed this - yes, I'll take a look - thanks!

**Comment by MKoppJones** [comment]
First off, quick apology from @CoburnJoe regarding the delay, we have been completely swamped so have only just gotten around to checking this out.

The [skip-init-on-disabled](https://github.com/alisaifee/flask-limiter/tree/skip-init-on-disabled) branch does solve the issue here 🎉 . Would love to see this as part of the main project 👍

**Comment by alisaifee** [comment]
@MKoppJones no worries at all - I'll merge that by end of week and make a release.

**Comment by CoburnJoe** [comment]
@alisaifee any sign of a release for this change? 😃

**Comment by alisaifee** [comment]
Released in version 1.4 [here](https://pypi.org/project/Flask-Limiter/1.4/)
