### ISSUE TITLE
[Question] Is it possible to limit what headers are sent when headers enabled?

### ISSUE THREAD

**Issue by VeNoMouS** [alisaifee/flask-limiter#279]
Is it possible to send **__only__** `Retry-After` without 

```
X-RateLimit-Limit
X-RateLimit-Remaining
X-RateLimit-Reset
```

Because my understanding is even if i set a custom error handler with "headers disabled", i don't have anyway to access the remaining time to manually send a header for `Retry-After`

**Comment by alisaifee** [comment]
The header controls are in a pretty bad state with some inconsistency between the things you can set via flask config, and those that you can control with the `Limiter` constructor. 

At the moment you can set the name of the retry after header with `RATELIMIT_HEADER_REMAINING` in your flask config but you wouldn't be able to disable the others. 

I'll (finally) clean this up so that you can control which headers to enable, and also what to call them both via config and the constructor.

**Comment by alisaifee** [comment]
This has been addressed in version `2.1.x`. You can also construct the headers yourself with an `after_request` hook by using the `current_limit` or `current_limits` attributes of the extension which expose which limits were evaluated and their details for the current request.
