### ISSUE TITLE
Add application_limits_exempt_when?

### ISSUE THREAD

**Issue by pb-jeff-oneill** [alisaifee/flask-limiter#295]
It seems that 

> default_limits_exempt_when

does not apply to application limits set with

> application_limits

I'm using only application limits and I need to be able to exempt security scanners and things like that.

Is there a plan to add an `application_limits_exempt_when` option?

Or is there another way to accomplish that?

**Comment by pb-jeff-oneill** [comment]
Ah, I missed that you can use a callable to specify limits and that is exactly what I need.

Thanks for providing such a great tool!

**Comment by etiennecaldichouryatnapta** [comment]
Hi!
I have the same need: I want to exclude some requests from the application_limits.
But it doesn't seem like using a callable for specifying limits solves the issue?
Because this callback won't be called at each request? (it is the case for `default_limits_exempt_when`, so it would be awesome to have a `application_limits_exempt_when `!
I'll check the code but if someone has an idea to make this work with the actual code it would be great!
