### ISSUE TITLE
Website is down when REDIS remote servers are unavailable

### ISSUE THREAD

**Issue by steopcik** [alisaifee/flask-limiter#319]
Hi!
I use Flask-Limiter with a remote REDIS server.
The only place I need the limiter is the request forms.
I did one test to see what happens when servers are not reachable. 
If Redis servers are down, all users see a 500 error message on the entire website. 
I need to set up an optional security layer more than required with the rate-limiting option. 
To avoid user website usage disruption. 

Is there an option to bypass the limit check if the Redis server does not respond in one or two seconds?

By adding to config option like "**bypass_if_server_not_respond='2sec'**"
```
limiter = Limiter(
    app,
    key_func=get_remote_address,
    default_limits=["6000 per day", "240 per hour"],
    storage_uri='redis://:password@1.1.1.1:6379',
    bypass_if_server_not_respond='2sec',
    key_prefix='ipt'
)
```

**Comment by alisaifee** [comment]
Though the support doesn't go as far as allowing you to configure exact timeouts before bypassing, you can configure the limiter to swallow errors with the upstream with using the [SWALLOW_ERRORS](https://flask-limiter.readthedocs.io/en/stable/configuration.html#RATELIMIT_SWALLOW_ERRORS) configuration.  Would that work for your usecase?

**Comment by steopcik** [comment]
It works as I expected.
Timeout is high, in my opinion, ~5 seconds.

@alisaifee Thank you!

**Comment by alisaifee** [comment]
No worries. Regarding the timeout you can configure it based on what makes sense in your setup by passing any of the extra arguments that `redis.Redis` accepts via the `storage_options` argument to the `Limiter` constructor.

For example:
```
Limiter(....., storage_uri="redis://localhost:6379", storage_options={"socket_timeout": 0.1})
```
More details [here](https://redis-py.readthedocs.io/en/latest/connections.html#redis.Redis)

The swallow errors / fallback to memory (using [RATE_LIMIT_IN_MEMORY_FALLBACK_ENABLED](https://flask-limiter.readthedocs.io/en/stable/configuration.html#RATELIMIT_IN_MEMORY_FALLBACK_ENABLED)) implementations were written a long time ago and I haven't updated it much since. For instance at the moment if you only enable `swallow_errors` without a fallback limiter, every request that is marked rate limitable will still attempt to talk to your redis instance - however, if there is a fallback enabled,  a rudimentary exponential backoff is used to check if the fallback should continue to be used or if the redis (or whatever) storage is back up and can be used again.

If you have any feedback/suggestions on failure mode handling - I think that part of the extension could benefit from some updates.
