### ISSUE TITLE
Not working on Heroku, working in localhost

### ISSUE THREAD

**Issue by karaburmication** [alisaifee/flask-limiter#352]
So, my rate limiting works perfectly in my local environment, but it doesn't work in Heroku.

Flask-Limiter==2.6.0
worker - 1 (because someone pointed out that having multiple workers can cause this issue)

Content of my procfile:
web: newrelic-admin run-program gunicorn --workers 1 app:app --preload

`limiter = Limiter(app, key_func=get_remote_address)`

...

`@blueprint.route('/process', methods=['GET', 'POST'])

@limiter.limit("150 per 1 day", error_message='150req/1d')
@limiter.limit("100 per 3 hour", error_message='100req/3h')
@limiter.limit("75 per 2 hour", error_message='75req/2h')
@limiter.limit("50 per 1 hour", error_message='50req/1h')
@limiter.limit("20 per 15 minute", error_message='20req/15m')
@limiter.limit("10 per 5 minute", error_message='10req/5m')`

Does anyone know what seems to be the problem?

**Comment by alisaifee** [comment]
Could you clarify a bit more by what you mean by "doesn't work in Heroku?".

**Comment by karaburmication** [comment]
> Could you clarify a bit more by what you mean by "doesn't work in Heroku?".

No limit is set for any of my requests for production app in Heroku, meaning that nothing is rate limited even though it should be. Identical settings work without any issues in my local environment.

I got it resolved by using Redis to store key/value pairs. Nothing else was changed, only the storage location.

**Comment by alisaifee** [comment]
Ah got it! Using the in-memory limiter means each worker process has it's own rate limiter.

Another thing to note when using Heroku though is that the simple `get_remote_address` method will not work properly since your application is actually behind a proxy. Refer to [the recipe for deploying an application behind a proxy](https://flask-limiter.readthedocs.io/en/stable/recipes.html#deploying-an-application-behind-a-proxy) for some tips.

**Comment by alisaifee** [comment]
Closing as no action pending
