### ISSUE TITLE
Auto-Cache Clean / Garbage Collection

### ISSUE THREAD

**Issue by stealthco-tony** [alisaifee/flask-limiter#458]
## Expected Behaviour

Expect the service to automatically clean the cache once the rate_limit has expired (for the given Key). For example, if the `key_func` is IP Address, and we set a limit of 1 time per hour, once Flask limiter determines the hour has passed, it should clear the cache. There is no point/need in keeping old requests that are outside the limiting time period once the period has passed (if anything, they should be logged in a more persistent storage, not memorystorage).

For v1 of this new feature, I would expect it to check on every call of the decorated route(s). For v2, you could spin off a separate microservice that is constantly monitoring and clearing caches (even a paid upgrade).

Thanks!

**Comment by Shellcat-Zero** [comment]
I was about to ask about this because I couldn't find an answer in the documentation. Does the memory keep filling up then, the longer that the flask app is running? I would expect periodic garbage collection, at the very least, probably when receiving another event that checks the limiter, and then at that time the limiter deletes expired entries. If doing it on every event might be too expensive, then there probably needs to be some configurable parameter to clean the cache every N events, or something similar.

**Comment by alisaifee** [comment]
@stealthco-tony / @Shellcat-Zero - there are various persistent storages that can be configured to be used with flask limiter that would give you said expiry of unused keys. The memory storage does also periodically expire entries ([reference](https://github.com/alisaifee/limits/blob/master/limits/storage/memory.py#L55)), however as is specified in the documentation, the memory storage backend is a only a reference implementation and is not meant to be used in production.
