### ISSUE TITLE
global_limits are per-route, not shared

### ISSUE THREAD

**Issue by olasd** [alisaifee/flask-limiter#63]
Hi,

When using flask-limiter, I expected that the global limits would be a limit shared by all routes, rather than a default per-route limit.

You might want to clarify documentation on this subject :)

Thanks!

**Comment by lukas-gitl** [comment]
Wait, it is not?! How would I achieve a limit shared by all routes then?

**Comment by alisaifee** [comment]
Sorry for the delay in getting to this issue.

@olasd you are right, maybe the name should have been `default_limits` - having said that I can't change it now since it would probably break other people's software.

What I can propose is a new `application_limits` configuration that actually does get applied as a shared limit for all routes. What do you think?

**Comment by lukas-gitl** [comment]
That would be great @olasd.

I would also recommend deprecating and renaming the parameter. I'm sure we are not the only people getting confused here (!).

**Comment by alisaifee** [comment]
@lukas-gitl / @olasd could I trouble you to take a look at the implementation in https://github.com/alisaifee/flask-limiter/tree/f-global-shared-limits that implements an application wide shared limit.

**Comment by lukas-gitl** [comment]
FYI: I started using the shared limiter, and applied it to all routes.
