### ISSUE TITLE
Can't use dynamic limit in `default_limits`

### ISSUE THREAD

**Issue by lukas-gitl** [alisaifee/flask-limiter#94]
Pretty much what the topic says. If I try to use function in the list that I pass to default_limits in the constructor it throws an error.

**Comment by brunobell** [comment]
@lukas-gitl Just like in #96 you have to pass the return of the function, which is expected to be a list of limit strings in this case.

**Comment by lukas-gitl** [comment]
Not true. See comment in #96

**Comment by lukas-gitl** [comment]
I would expect something like this to work:

```python
from flask import Flask
from flask_limiter import Limiter

app = Flask(__name__)
limiter = Limiter(app, default_limits=[lambda: "1/1minute"])


@app.route("/")
@limiter.limit("10/1minute")
def slow():
    return "index"

if __name__ == '__main__':
    app.run(debug=True, port=5000)

```

(this time I tested with a clean env...)

**Comment by brunobell** [comment]
@lukas-gitl I do not know why you never post any error log in your issue.

**Comment by brunobell** [comment]
@alisaifee Hi I traced down this issue and found that default_limits deals with strings only in the limits package `[parse_many](https://github.com/alisaifee/limits/raw/master/limits/util.py)`. This would not be hard to fixed to enable passing functions/lambdas to this init config making it a dynamic limit, just add evaluate it if the value of keyword argument default_limits is callable.
Which do you think is more appropriate to fix, that would be less likely to cause potential break in projects using older versions of limits/flask-limiter? I'd like to make a pr for this if you'd like it.
Happy to hear your comments.

**Comment by lukas-gitl** [comment]
@brunobell Thank for getting back! I didn't post logs because (1) #96 was not actually an issue and (2) the simple example posted in https://github.com/alisaifee/flask-limiter/issues/94#issuecomment-337318827 crashes reliable (for everyone).

Why would this break anything? As far as I understand it's purely additive?

**Comment by alisaifee** [comment]
Sorry for the delay in getting back on this issue. 

The `parse_many` function in `limits` is expected to only ever receive a string like object so the delayed extraction of the string does indeed belong in the extension itself. I've added some assertions to `parse_limit` in `limits` though so that it raises a domain specific exception now.

To address the missing functionality - `default_limits`, `application_limits` and `in_memory_fallback` can now take either a list of strings or callables that return strings (or a combination).  I haven't added these as examples in the documentation yet but you can refer to the following two test cases to see how this works (inspired by the test case shared by @lukas-gitl):
 - https://github.com/alisaifee/flask-limiter/blob/master/tests/test_flask_ext.py#L912
 - https://github.com/alisaifee/flask-limiter/blob/master/tests/test_flask_ext.py#L930

**Comment by lukas-gitl** [comment]
@alisaifee Sweet! Thank you very much!

**Comment by lukas-gitl** [comment]
We just added this in. Works exactly as expected. Cheers!
